### ISSUE TITLE
Issue with emacs after linkall (ubuntu 15.04 64bit)

### ISSUE THREAD

**Issue by nedzadk** [aaronbieber/dotfiles#1]
![hp5225](https://cloud.githubusercontent.com/assets/646932/8032990/18677e5a-0ddb-11e5-8b8b-d456845f5b85.png)

Once i comment octopress in .emacs i get another error similar to this but just different package. 
What am i doing wrong

**Comment by aaronbieber** [comment]
This repo is my personal configuration files, which are in a constant state of change. I can't make any guarantees that this package will even work for anyone else most of the time.

As it says, it can't find a particular file because I am working on developing that new mode and so it lives in its own repo for now. Follow the suggestion and start Emacs with `--debug-init` to track down where the offending statement is and comment it out.

**Comment by nedzadk** [comment]
don't take this the wrong way, i was watching your video about emacs and decided to give it a shot :) so i figured i should try your dotfile :) 
I will try to make it work... :)

**Comment by aaronbieber** [comment]
The Emacs part should work fine on Emacs 25 once you comment out the octopress reference. I'm going to be moving that out of dotfiles soon anyway. 

Good luck!
