### ISSUE TITLE
air-org-set-tags--why use delq ""?

### ISSUE THREAD

**Issue by rieje** [aaronbieber/dotfiles#8]
In your `air-org-set-tags` function [here](https://github.com/aaronbieber/dotfiles/blob/ed4f31143b2153ef2ff0d78af1c5d60c7430339e/configs/emacs.d/lisp/init-org.el#L482), why did you use `delq ""`? [This guy](https://github.com/telotortium/emacs.d/blob/a6ccc8bbf34bf111ab24db55be17bf387f627d9a/init.el#L959) uses the same function but omitted it. Just curious--is it redundant?

P.S. I came across this from your blog and you also mentioned internal functions have double hyphens in their name as a convention. I have the follow [code](https://ptpb.pw/AJ_jSAOVSV6790c6Hu_XXtRh8Fp0) is the function considered an "internal function" and should it have double hyphens? It's not really a helper function (right?) but it's also not an interactive function, so I'm not sure whether to use double hyphens for best practices.

Thanks.

**Comment by aaronbieber** [comment]
`C-h f delq<RET>` will open the manual page for the `delq` function. There, it says:

> Delete members of LIST which are ‘eq’ to ELT, and return the result.
More precisely, this function skips any members ‘eq’ to ELT at the
front of LIST, then removes members ‘eq’ to ELT from the remaining
sublist by modifying its list structure, then returns the resulting
list.

I must have done this because `org-get-tags` returns some empty strings and I didn't want to present those as selectable options.

To your second question, the double hyphen is a convention that is generally known to mean that the function is not to be used by the user themselves. Typically these are utility functions called directly by other functions. There are no hard and fast rules about this, it is part of your package's API design.
